# Generated by Django 4.2.4 on 2024-06-12 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_message_reactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='message.message'),
        ),
    ]
