version: '3.8'

services:
  backend:
    image: chat_app_backend
    build:
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    depends_on:
      - database
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: main
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - 33066:3306