# Generated by Django 4.2.4 on 2024-04-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='type',
            field=models.CharField(choices=[('CHAT', 'Trò chuyện'), ('COMMUNITY', 'Cộng đồng')], default='COMMUNITY', max_length=20),
        ),
    ]
