# Generated by Django 4.2.4 on 2024-05-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_channel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
