# Generated by Django 4.2.4 on 2024-05-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expo_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
